= backend

I assume java dev kit and runtime is installed and you are running under nix like OS.

== run the CLI(command line interface)

to run the cli, launch this command in the terminal, add needed arguments to fit the requirement
[source,bash]
----
./gradlew -q bootRun --args='example1/millennium-falcon.json example1/empire.json'
----


== run backend

to run backend locally, launch this command in terminal and go to http://localhost:8080
[source,bash]
----
./gradlew computer
----
to stop the backend use Ctrl+C


== test backend
to test backend, run this command in terminal
[source,bash]
----
./gradlew check;
----

test report is available from the root project folder follow this path: backend/build/reports/tests/test/index.html



== deploy to google cloud

=== install gcloud cli on ubuntu/debianLike
[source,bash]
----
snap remove google-cloud-sdk
snap install google-cloud-cli --classic
----

=== setup google credentials
[source,bash]
----
gcloud init
----


=== deploy to google app engine
to deploy backend on google app engine, run this command in terminal
[source,bash]
----
./gradlew :backend:deployGAE
----

==== Available tasks and descriptions
[source,bash]
----
./gradlew tasks
----

== Algorithm approach

to solve the problem let's use the Dijkstra’s algorithm who answers the question +
of the shortest and fastest paths for travelers. +


according to our universe.csv
[%header,format=csv,separator=";"]
|===
origin;destination;travel_time
Tatooine;Dagobah;6
Dagobah;Endor;4
Dagobah;Hoth;1
Hoth;Endor;1
Tatooine;Hoth;6
|===

vertex :
|===
|starting vertex: days from start |Tattoine|Dagobah | Endor | Hoth
|Tatooine
|--
|6
|4
|6
|Dagobah
|6
|--
|4
|1
|Hoth
|6
|1
|1
|--
|Endor
|--
|4
|--
|1
|===

lowest-cost-path

