backend:
  message: hello
  item: item
  clientApp:
    name: 'server'
  database:
    populator-path: db/tables.sql
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: false
    max-age: 1800
server:
  port: 8080
spring:
  application:
    name: server
  profiles:
    default: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: r2dbc:h2:mem:backend;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  devtools:
    restart:
      enabled: true
  thymeleaf:
    mode: HTML
  messages:
    basename: i18n/messages
    encoding: UTF-8
  main:
    banner-mode: "off"
  http:
    multipart:
      enabled: true
      location: /api/give-me-the-odds
logging:
  level:
    org:
      springframework:
        r2dbc: WARN
        org.hibernate.SQL: WARN



