-- noinspection SqlNoDataSourceInspectionForFile
CREATE TABLE IF NOT EXISTS `ROUTES` (
    `ID`          UUID default random_uuid() PRIMARY KEY,
    `ORIGIN`      VARCHAR,
    `DESTINATION` VARCHAR,
    `TRAVEL_TIME` INT
);
CREATE UNIQUE INDEX IF NOT EXISTS `UNIQUE_IDX_ORIGIN_DESTINATION`
ON `ROUTES` (`ORIGIN`, `DESTINATION`);
